spring:
  profiles:
    active: local
  application:
    name: events-service

  liquibase:
      change-log: classpath:/db/changelog/db.changelog-master.sql

  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    context-path: /events-service

jasypt:
  encryptor:
    password: CddTYuNbEKavHdzssRyQf2gTCLq

jkspassword: test

---
spring:
  profiles: local
  autoconfigure:
    jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
      format_sql: true
      show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        id:
          new_generator_mappings: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:event;MODE=PostgreSQL;
    username: sa
    password:
  h2:
    console:
      enabled: true
---
spring:
  profiles: dev

---
spring:
  profiles: qa

---
spring:
  profiles: qa-east

---
spring:
  profiles: qa-west

---
spring:
  profiles: perf

---
spring:
  profiles: prod

---
spring:
  profiles: prod-east

---
spring:
  profiles: prod-west

---
spring:
  profiles: remote-AT
  main:
    web-application-type: none